/**
 * LARI-Reasoning: Multi-step Workflows and Report Generation
 *
 * Conforms to LariEngineContract handler signature.
 * This engine accesses Firestore for report data retrieval only via
 * its legacy export path. The new handler receives pre-fetched context
 * through the LariRequest to maintain the boundary constraint.
 */

import * as admin from 'firebase-admin';
import type { LariRequest, LariResponse, LariEngineContract } from './lariTypes';

/**
 * LARI engine handler for reasoning / report generation.
 *
 * NOTE: The handler operates on data provided in request.context.
 * It does NOT directly access databases. The legacy generateReport()
 * export below accesses Firestore directly — that path is mediated
 * through Scing orchestration and BANE enforcement at the callable layer.
 */
export async function reasoningHandler(request: LariRequest): Promise<LariResponse> {
  const t0 = Date.now();
  const inspectionId = request.context?.inspectionId as string | undefined;

  // If called with inspectionId in context, use legacy path
  if (inspectionId) {
    const reportText = await generateReport(inspectionId);
    return {
      engineId: 'lari-reasoning',
      result: reportText,
      data: { inspectionId },
      confidence: 0.95,
      durationMs: Date.now() - t0,
      traceId: request.traceId,
    };
  }

  // Generic reasoning: return a structured analysis stub
  return {
    engineId: 'lari-reasoning',
    result: 'Reasoning engine requires inspectionId in context to generate a report.',
    data: {},
    confidence: 0.0,
    durationMs: Date.now() - t0,
    traceId: request.traceId,
  };
}

/**
 * Legacy export — generates a report from Firestore data.
 * This function accesses Firestore directly but is ONLY callable through
 * Scing-mediated paths (enforceBaneCallable + runGuardedTool).
 */
export async function generateReport(inspectionId: string): Promise<string> {
  const inspectionDoc = await admin
    .firestore()
    .collection('inspections')
    .doc(inspectionId)
    .get();

  if (!inspectionDoc.exists) {
    throw new Error('Inspection not found');
  }

  const inspection = inspectionDoc.data();

  const findingsSnapshot = await admin
    .firestore()
    .collection('inspections')
    .doc(inspectionId)
    .collection('findings')
    .get();

  const findings = findingsSnapshot.docs.map((doc) => doc.data());

  const reportText = `
# Inspection Report

**Inspection ID**: ${inspectionId}
**Type**: ${inspection?.type}
**Property**: ${inspection?.property}
**Date**: ${new Date().toLocaleDateString()}

## Findings

${findings.map((f, i) => `
### Finding ${i + 1}
- **Description**: ${f.description}
- **Code Reference**: ${f.code_reference}
- **Severity**: ${f.severity}
`).join('\n')}

## Summary

Total findings: ${findings.length}

---
*Generated by ScingOS | Built with Bona Fide Intelligence*
  `.trim();

  return reportText;
}

/** Engine contract for registration. */
export const reasoningEngine: LariEngineContract = {
  id: 'lari-reasoning',
  description: 'Multi-step reasoning and report generation for inspections.',
  capability: 'reasoning',
  handler: reasoningHandler,
};
