import {
  EngineCapability,
  EngineFamily,
  EngineId,
  EngineRuntime,
  EngineStage,
  EngineTier,
} from './engineTypes';
import type { ExecutionClass } from './executionClass';

export type EngineRecord = {
  id: EngineId;
  title: string;
  tier: EngineTier;
  family: EngineFamily;
  runtime: EngineRuntime;
  stage: EngineStage; // A/B/NA
  executionClass: ExecutionClass;
  capabilities: EngineCapability[];
  description: string;
  dependsOn: EngineId[];
  providesKeys?: string[]; // entitlement handles like "vision.stage", "mapper.stage"
  authorityScope: string; // explicit authority description for this engine
  permittedInputs: string[]; // categories of input this engine may receive
  permittedOutputs: string[]; // categories of output this engine may produce
  executionRestrictions: string[]; // explicit prohibitions
  auditRequirements: string[]; // audit obligations
  flags: {
    enabledByDefault: boolean;
    canRunOffline: boolean;
    requiresExternalHardware: boolean;
  };
  version: {
    schema: string; // contract/schema version for this engine
    impl: string; // implementation version
  };
};

export const REGISTRY_VERSION = '1.0.0-canon';

export const ENGINE_REGISTRY: Record<EngineId, EngineRecord> = {
  SCING: {
    id: 'SCING',
    title: 'SCING Presentation & Reporting',
    tier: 'core',
    family: 'scing',
    runtime: 'hybrid',
    stage: 'NA',
    executionClass: 'reporting',
    capabilities: ['report', 'audit'],
    description: 'UI/HUD + dynamic investor/regulator-grade reporting pipelines.',
    dependsOn: ['LARI', 'BANE'],
    authorityScope: 'Presentation and reporting only. No reasoning, enforcement, or capture.',
    permittedInputs: ['artifacts', 'telemetry', 'findings', 'classifications', 'map_layers', 'policy'],
    permittedOutputs: ['report_blocks', 'audit_events'],
    executionRestrictions: ['Must not perform domain reasoning', 'Must not enforce policy'],
    auditRequirements: ['Log all report generation events'],
    flags: { enabledByDefault: true, canRunOffline: true, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  LARI: {
    id: 'LARI',
    title: 'Learning & Adaptive Regulatory Intelligence',
    tier: 'core',
    family: 'lari',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'reasoning',
    capabilities: ['analyze', 'classify', 'fuse', 'audit'],
    description:
      'Central intelligence: fuses sensor data and codes/standards into decisions + guidance.',
    dependsOn: ['BANE'],
    authorityScope: 'Reasoning and analysis only. No direct action, no enforcement, no tool execution.',
    permittedInputs: ['intent_vector', 'semantic_map', 'constraint_map', 'artifacts', 'telemetry', 'geo', 'weather', 'policy', 'keys'],
    permittedOutputs: ['findings', 'classifications', 'policy_flags', 'audit_events'],
    executionRestrictions: ['Must not execute tools', 'Must not mutate databases', 'Must not enforce policy'],
    auditRequirements: ['Log all reasoning invocations', 'Produce EngineTrace per invocation'],
    flags: { enabledByDefault: true, canRunOffline: false, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  BANE: {
    id: 'BANE',
    title: 'Boundary, Authorization & Network Enforcement',
    tier: 'core',
    family: 'bane',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'enforcement',
    capabilities: ['enforce', 'audit'],
    description: 'Security, licensing keys, zero-trust enforcement, chain-of-custody controls.',
    dependsOn: [],
    authorityScope: 'Boundary enforcement only. Does not reason or replace reasoning.',
    permittedInputs: ['intent_vector', 'policy', 'keys', 'telemetry', 'geo', 'weather'],
    permittedOutputs: ['policy_flags', 'audit_events'],
    executionRestrictions: ['Must not perform domain reasoning', 'Must not generate reports'],
    auditRequirements: ['Log all enforcement decisions', 'Produce EngineVerdict per evaluation'],
    flags: { enabledByDefault: true, canRunOffline: false, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  'LARI-VISION': {
    id: 'LARI-VISION',
    title: 'Vision Key',
    tier: 'key',
    family: 'lari-key',
    runtime: 'hybrid',
    stage: 'A',
    executionClass: 'sensing',
    capabilities: ['capture', 'analyze', 'audit'],
    description:
      'Camera/video capture + on-device detection + OCR + evidence watermarking; Stage B adds external camera adapters.',
    dependsOn: ['BANE', 'LARI'],
    providesKeys: ['vision.stage'],
    authorityScope: 'Visual signal capture and translation. Analysis delegated to LARI.',
    permittedInputs: ['artifacts', 'telemetry', 'policy', 'keys', 'geo'],
    permittedOutputs: ['artifacts', 'findings', 'audit_events'],
    executionRestrictions: ['Must not enforce policy', 'Must not issue verdicts'],
    auditRequirements: ['Log all capture events with evidence chain'],
    flags: { enabledByDefault: true, canRunOffline: true, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  'LARI-MAPPER': {
    id: 'LARI-MAPPER',
    title: 'Mapper (LiDAR) Key',
    tier: 'key',
    family: 'lari-key',
    runtime: 'hybrid',
    stage: 'A',
    executionClass: 'sensing',
    capabilities: ['capture', 'map', 'analyze', 'audit'],
    description:
      'On-device LiDAR/ToF mapping (Stage A) and external LiDAR rigs (Stage B) with GIS alignment.',
    dependsOn: ['BANE', 'LARI', 'LARI-GIS'],
    providesKeys: ['mapper.stage'],
    authorityScope: 'Spatial signal capture and point-cloud translation.',
    permittedInputs: ['artifacts', 'telemetry', 'policy', 'keys', 'geo'],
    permittedOutputs: ['artifacts', 'map_layers', 'findings', 'audit_events'],
    executionRestrictions: ['Must not enforce policy', 'Must not issue verdicts'],
    auditRequirements: ['Log all mapping sessions with spatial metadata'],
    flags: { enabledByDefault: true, canRunOffline: true, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  'LARI-DOSE': {
    id: 'LARI-DOSE',
    title: 'Drone Key',
    tier: 'key',
    family: 'lari-key',
    runtime: 'hybrid',
    stage: 'NA',
    executionClass: 'sensing',
    capabilities: ['capture', 'control', 'map', 'audit'],
    description:
      'Aerial imagery + telemetry collection with safety gates (weather/geofence); integrates closed-loop control.',
    dependsOn: ['BANE', 'LARI', 'LARI-CONTROL', 'LARI-WEATHERBOT', 'LARI-GIS'],
    providesKeys: ['dose.enabled'],
    authorityScope: 'Aerial capture and telemetry relay. Control delegated to LARI-CONTROL.',
    permittedInputs: ['telemetry', 'policy', 'keys', 'geo', 'weather'],
    permittedOutputs: ['artifacts', 'telemetry', 'control_events', 'audit_events'],
    executionRestrictions: ['Must not perform domain analysis', 'Must not override BANE safety gates'],
    auditRequirements: ['Log all flight events', 'Emit geo-tagged telemetry'],
    flags: { enabledByDefault: false, canRunOffline: true, requiresExternalHardware: true },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  'LARI-PRISM': {
    id: 'LARI-PRISM',
    title: 'Spectrometer Key',
    tier: 'key',
    family: 'lari-key',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'sensing',
    capabilities: ['ingest', 'classify', 'audit'],
    description: 'Material/chemical composition classification from spectral inputs.',
    dependsOn: ['BANE', 'LARI'],
    providesKeys: ['prism.enabled'],
    authorityScope: 'Spectral signal ingestion and classification.',
    permittedInputs: ['artifacts', 'telemetry', 'policy', 'keys', 'geo'],
    permittedOutputs: ['classifications', 'findings', 'audit_events'],
    executionRestrictions: ['Must not enforce policy'],
    auditRequirements: ['Log all spectral analysis sessions'],
    flags: { enabledByDefault: false, canRunOffline: false, requiresExternalHardware: true },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  'LARI-ECHO': {
    id: 'LARI-ECHO',
    title: 'Sonar Key',
    tier: 'key',
    family: 'lari-key',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'sensing',
    capabilities: ['ingest', 'map', 'analyze', 'audit'],
    description: 'Acoustic imaging for hidden/submerged structure mapping and defect detection.',
    dependsOn: ['BANE', 'LARI', 'LARI-GIS'],
    providesKeys: ['echo.enabled'],
    authorityScope: 'Acoustic signal ingestion and spatial mapping.',
    permittedInputs: ['artifacts', 'telemetry', 'policy', 'keys', 'geo'],
    permittedOutputs: ['artifacts', 'map_layers', 'findings', 'audit_events'],
    executionRestrictions: ['Must not enforce policy'],
    auditRequirements: ['Log all acoustic capture sessions'],
    flags: { enabledByDefault: false, canRunOffline: false, requiresExternalHardware: true },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  'LARI-CONTROL': {
    id: 'LARI-CONTROL',
    title: 'CCLoop Control Plane',
    tier: 'platform',
    family: 'lari-platform',
    runtime: 'edge',
    stage: 'NA',
    executionClass: 'enforcement',
    capabilities: ['control', 'enforce', 'audit'],
    description:
      'Edge-only hot loop controller bus for safe device control; async signed telemetry to server.',
    dependsOn: ['BANE'],
    authorityScope: 'Device control enforcement at the edge. No domain reasoning.',
    permittedInputs: ['telemetry', 'policy', 'keys', 'geo', 'weather'],
    permittedOutputs: ['control_events', 'audit_events'],
    executionRestrictions: ['Must not perform domain reasoning', 'Must not generate reports'],
    auditRequirements: ['Log all control loop events', 'Sign telemetry for chain-of-custody'],
    flags: { enabledByDefault: true, canRunOffline: true, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  'LARI-WEATHERBOT': {
    id: 'LARI-WEATHERBOT',
    title: 'Weather & Hazard Sub-Engine',
    tier: 'platform',
    family: 'lari-platform',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'sensing',
    capabilities: ['ingest', 'analyze', 'enforce', 'audit'],
    description:
      'Authoritative weather/hazard ingestion and normalization for safety gating and report context.',
    dependsOn: ['BANE'],
    authorityScope: 'Weather and hazard data ingestion. Safety gating delegated to BANE.',
    permittedInputs: ['geo', 'policy'],
    permittedOutputs: ['weather', 'policy_flags', 'audit_events'],
    executionRestrictions: ['Must not perform domain reasoning beyond weather normalization'],
    auditRequirements: ['Log all weather data fetches with source attribution'],
    flags: { enabledByDefault: true, canRunOffline: false, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  'LARI-GIS': {
    id: 'LARI-GIS',
    title: 'Geospatial Sub-Engine',
    tier: 'platform',
    family: 'lari-platform',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'sensing',
    capabilities: ['ingest', 'fuse', 'map', 'audit'],
    description:
      'Geospatial fusion: maps/parcels/overlays; aligns LiDAR/drone/sonar outputs to ground truth.',
    dependsOn: ['BANE'],
    authorityScope: 'Geospatial data fusion and alignment. No domain reasoning.',
    permittedInputs: ['geo', 'artifacts', 'telemetry', 'policy'],
    permittedOutputs: ['map_layers', 'audit_events'],
    executionRestrictions: ['Must not perform domain analysis', 'Must not enforce policy'],
    auditRequirements: ['Log all geospatial fusion operations'],
    flags: { enabledByDefault: true, canRunOffline: false, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  // Roadmap keys (present in registry now; enabled later)
  'LARI-THERM': {
    id: 'LARI-THERM',
    title: 'Thermal Imaging Key',
    tier: 'roadmap',
    family: 'lari-key',
    runtime: 'hybrid',
    stage: 'NA',
    executionClass: 'sensing',
    capabilities: ['capture', 'analyze', 'audit'],
    description: 'Infrared thermal capture + anomaly detection.',
    dependsOn: ['BANE', 'LARI', 'LARI-GIS'],
    providesKeys: ['therm.enabled'],
    authorityScope: 'Thermal signal capture and anomaly surfacing.',
    permittedInputs: ['artifacts', 'telemetry', 'policy', 'keys', 'geo'],
    permittedOutputs: ['artifacts', 'findings', 'audit_events'],
    executionRestrictions: ['Must not enforce policy'],
    auditRequirements: ['Log all thermal capture sessions'],
    flags: { enabledByDefault: false, canRunOffline: true, requiresExternalHardware: true },
    version: { schema: '1.0.0', impl: '0.0.0' },
  },

  'LARI-NOSE': {
    id: 'LARI-NOSE',
    title: 'Gas Sniffer Key',
    tier: 'roadmap',
    family: 'lari-key',
    runtime: 'hybrid',
    stage: 'NA',
    executionClass: 'sensing',
    capabilities: ['ingest', 'analyze', 'enforce', 'audit'],
    description: 'Real-time gas detection + concentration thresholds + alerts.',
    dependsOn: ['BANE', 'LARI', 'LARI-CONTROL', 'LARI-WEATHERBOT'],
    providesKeys: ['nose.enabled'],
    authorityScope: 'Gas concentration signal ingestion and threshold alerting.',
    permittedInputs: ['telemetry', 'policy', 'keys', 'geo'],
    permittedOutputs: ['findings', 'policy_flags', 'audit_events'],
    executionRestrictions: ['Must not override BANE safety gates'],
    auditRequirements: ['Log all gas detection events with concentrations'],
    flags: { enabledByDefault: false, canRunOffline: true, requiresExternalHardware: true },
    version: { schema: '1.0.0', impl: '0.0.0' },
  },

  'LARI-SONIC': {
    id: 'LARI-SONIC',
    title: 'Ultrasonic NDT Key',
    tier: 'roadmap',
    family: 'lari-key',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'sensing',
    capabilities: ['ingest', 'analyze', 'audit'],
    description: 'Ultrasonic non-destructive testing for thickness/cracks/weld integrity.',
    dependsOn: ['BANE', 'LARI'],
    providesKeys: ['sonic.enabled'],
    authorityScope: 'Ultrasonic signal ingestion and thickness measurement.',
    permittedInputs: ['artifacts', 'telemetry', 'policy', 'keys', 'geo'],
    permittedOutputs: ['findings', 'audit_events'],
    executionRestrictions: ['Must not enforce policy'],
    auditRequirements: ['Log all NDT sessions with calibration data'],
    flags: { enabledByDefault: false, canRunOffline: false, requiresExternalHardware: true },
    version: { schema: '1.0.0', impl: '0.0.0' },
  },

  'LARI-GROUND': {
    id: 'LARI-GROUND',
    title: 'Ground-Penetrating Radar Key',
    tier: 'roadmap',
    family: 'lari-key',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'sensing',
    capabilities: ['ingest', 'map', 'analyze', 'audit'],
    description: 'Subsurface mapping and buried object/void detection.',
    dependsOn: ['BANE', 'LARI', 'LARI-GIS'],
    providesKeys: ['ground.enabled'],
    authorityScope: 'Ground-penetrating radar signal ingestion and subsurface mapping.',
    permittedInputs: ['artifacts', 'telemetry', 'policy', 'keys', 'geo'],
    permittedOutputs: ['map_layers', 'findings', 'audit_events'],
    executionRestrictions: ['Must not enforce policy'],
    auditRequirements: ['Log all GPR survey sessions'],
    flags: { enabledByDefault: false, canRunOffline: false, requiresExternalHardware: true },
    version: { schema: '1.0.0', impl: '0.0.0' },
  },

  'LARI-AEGIS': {
    id: 'LARI-AEGIS',
    title: 'Acoustic Emission Key',
    tier: 'roadmap',
    family: 'lari-key',
    runtime: 'hybrid',
    stage: 'NA',
    executionClass: 'sensing',
    capabilities: ['ingest', 'analyze', 'enforce', 'audit'],
    description: 'Structural health monitoring from stress-wave emissions.',
    dependsOn: ['BANE', 'LARI', 'LARI-CONTROL'],
    providesKeys: ['aegis.enabled'],
    authorityScope: 'Acoustic emission signal ingestion and structural health alerting.',
    permittedInputs: ['telemetry', 'policy', 'keys', 'geo'],
    permittedOutputs: ['findings', 'policy_flags', 'audit_events'],
    executionRestrictions: ['Must not override BANE safety gates'],
    auditRequirements: ['Log all AE monitoring sessions'],
    flags: { enabledByDefault: false, canRunOffline: true, requiresExternalHardware: true },
    version: { schema: '1.0.0', impl: '0.0.0' },
  },

  'LARI-EDDY': {
    id: 'LARI-EDDY',
    title: 'Eddy Current Key',
    tier: 'roadmap',
    family: 'lari-key',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'sensing',
    capabilities: ['ingest', 'analyze', 'audit'],
    description: 'Magnetic induction testing for cracks/corrosion/coating thickness.',
    dependsOn: ['BANE', 'LARI'],
    providesKeys: ['eddy.enabled'],
    authorityScope: 'Eddy current signal ingestion and defect detection.',
    permittedInputs: ['artifacts', 'telemetry', 'policy', 'keys', 'geo'],
    permittedOutputs: ['findings', 'audit_events'],
    executionRestrictions: ['Must not enforce policy'],
    auditRequirements: ['Log all eddy current inspection sessions'],
    flags: { enabledByDefault: false, canRunOffline: false, requiresExternalHardware: true },
    version: { schema: '1.0.0', impl: '0.0.0' },
  },

  // ---------------------------------------------------------------------------
  // Orchestration Family — SCING_ORCH and LARI_ORCH
  // ---------------------------------------------------------------------------

  'SCING-ORCH': {
    id: 'SCING-ORCH',
    title: 'Scing Orchestrator',
    tier: 'core',
    family: 'scing-orch',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'coordination',
    capabilities: ['coordinate', 'audit'],
    description:
      'Top-level orchestration shell. Routes requests through BANE, LARI, tools, and response synthesis. Scing coordinates; Scing does not reason as LARI and does not enforce as BANE.',
    dependsOn: ['BANE'],
    authorityScope: 'Request routing and pipeline coordination only. No reasoning, no enforcement.',
    permittedInputs: ['artifacts', 'telemetry', 'policy'],
    permittedOutputs: ['audit_events'],
    executionRestrictions: ['Must not perform domain reasoning', 'Must not enforce policy', 'Must not capture sensor data'],
    auditRequirements: ['Log all orchestration events', 'Emit EngineTrace per pipeline stage'],
    flags: { enabledByDefault: true, canRunOffline: false, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  'LARI-ORCH': {
    id: 'LARI-ORCH',
    title: 'LARI Orchestrator',
    tier: 'core',
    family: 'lari-orch',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'coordination',
    capabilities: ['coordinate', 'audit'],
    description:
      'Routes requests within the LARI reasoning federation (planner → critic → synthesizer). LARI-ORCH coordinates reasoning engines; it does not reason itself.',
    dependsOn: ['BANE', 'SCING-ORCH'],
    authorityScope: 'LARI pipeline routing and stage sequencing only. No reasoning authority.',
    permittedInputs: ['artifacts', 'telemetry', 'policy'],
    permittedOutputs: ['audit_events'],
    executionRestrictions: ['Must not perform domain reasoning', 'Must not enforce policy', 'Must not execute tools'],
    auditRequirements: ['Log all LARI pipeline routing decisions', 'Emit EngineTrace per stage'],
    flags: { enabledByDefault: true, canRunOffline: false, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  // ---------------------------------------------------------------------------
  // LARI Core Reasoning Family
  // ---------------------------------------------------------------------------

  'LARI-PLANNER': {
    id: 'LARI-PLANNER',
    title: 'LARI Planner Engine',
    tier: 'core',
    family: 'lari-reasoning',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'reasoning',
    capabilities: ['analyze', 'plan', 'audit'],
    description:
      'Decomposes requests into ordered reasoning steps. Returns a plan; does NOT execute it.',
    dependsOn: ['BANE', 'LARI-ORCH'],
    authorityScope: 'Plan decomposition only. No execution, no enforcement.',
    permittedInputs: ['intent_vector', 'semantic_map', 'constraint_map', 'artifacts', 'policy'],
    permittedOutputs: ['findings', 'audit_events'],
    executionRestrictions: ['Must not execute tools', 'Must not mutate state', 'Must not enforce policy'],
    auditRequirements: ['Log all planning invocations', 'Produce EngineTrace per invocation'],
    flags: { enabledByDefault: true, canRunOffline: false, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  'LARI-CRITIC': {
    id: 'LARI-CRITIC',
    title: 'LARI Critic Engine',
    tier: 'core',
    family: 'lari-reasoning',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'reasoning',
    capabilities: ['analyze', 'critique', 'audit'],
    description:
      'Validates reasoning outputs from planner and synthesizer. Issues quality/confidence assessments.',
    dependsOn: ['BANE', 'LARI-ORCH'],
    authorityScope: 'Reasoning validation only. No execution, no enforcement.',
    permittedInputs: ['findings', 'artifacts', 'policy'],
    permittedOutputs: ['findings', 'audit_events'],
    executionRestrictions: ['Must not execute tools', 'Must not mutate state', 'Must not enforce policy'],
    auditRequirements: ['Log all critic assessments', 'Produce EngineTrace per invocation'],
    flags: { enabledByDefault: true, canRunOffline: false, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  'LARI-SYNTHESIZER': {
    id: 'LARI-SYNTHESIZER',
    title: 'LARI Synthesizer Engine',
    tier: 'core',
    family: 'lari-reasoning',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'reasoning',
    capabilities: ['analyze', 'synthesize', 'audit'],
    description:
      'Synthesizes findings from planner and domain engines into a coherent reasoning output.',
    dependsOn: ['BANE', 'LARI-ORCH'],
    authorityScope: 'Reasoning synthesis only. No execution, no enforcement.',
    permittedInputs: ['findings', 'artifacts', 'classifications', 'policy'],
    permittedOutputs: ['findings', 'audit_events'],
    executionRestrictions: ['Must not execute tools', 'Must not mutate state', 'Must not enforce policy'],
    auditRequirements: ['Log all synthesis invocations', 'Produce EngineTrace per invocation'],
    flags: { enabledByDefault: true, canRunOffline: false, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  'LARI-CONTEXT-ENGINE': {
    id: 'LARI-CONTEXT-ENGINE',
    title: 'LARI Context Engine',
    tier: 'core',
    family: 'lari-reasoning',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'reasoning',
    capabilities: ['analyze', 'classify', 'audit'],
    description:
      'Enriches requests with domain context, keyword extraction, and session continuity.',
    dependsOn: ['BANE', 'LARI-ORCH'],
    authorityScope: 'Context enrichment and classification only. No execution.',
    permittedInputs: ['artifacts', 'telemetry', 'policy'],
    permittedOutputs: ['findings', 'classifications', 'audit_events'],
    executionRestrictions: ['Must not execute tools', 'Must not mutate state'],
    auditRequirements: ['Log all context enrichment invocations'],
    flags: { enabledByDefault: true, canRunOffline: false, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  'LARI-ANALYST': {
    id: 'LARI-ANALYST',
    title: 'LARI Analyst Engine',
    tier: 'core',
    family: 'lari-reasoning',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'reasoning',
    capabilities: ['analyze', 'interrogate', 'audit'],
    description:
      'Pattern interrogation, anomaly surfacing, and evidence weighting. Interrogates but does not authorize.',
    dependsOn: ['BANE', 'LARI-ORCH'],
    authorityScope: 'Pattern interrogation only. No execution, no enforcement.',
    permittedInputs: ['artifacts', 'telemetry', 'findings', 'policy'],
    permittedOutputs: ['findings', 'audit_events'],
    executionRestrictions: ['Must not execute tools', 'Must not enforce policy'],
    auditRequirements: ['Log all analytical interrogation sessions', 'Produce EngineTrace per invocation'],
    flags: { enabledByDefault: true, canRunOffline: false, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  'LARI-RETRIEVER': {
    id: 'LARI-RETRIEVER',
    title: 'LARI Retriever Engine',
    tier: 'core',
    family: 'lari-reasoning',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'reasoning',
    capabilities: ['analyze', 'ground', 'audit'],
    description:
      'Context grounding, data recovery, and relevant artifact fetch/scoping. Grounds but does not decide.',
    dependsOn: ['BANE', 'LARI-ORCH'],
    authorityScope: 'Information retrieval and grounding only. No execution decision.',
    permittedInputs: ['intent_vector', 'artifacts', 'policy'],
    permittedOutputs: ['artifacts', 'findings', 'audit_events'],
    executionRestrictions: ['Must not execute mutating tools', 'Must not formulate plans', 'Must not enforce policy'],
    auditRequirements: ['Log all retrieval invocations', 'Produce EngineTrace per invocation'],
    flags: { enabledByDefault: true, canRunOffline: false, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  // ---------------------------------------------------------------------------
  // BANE Enforcement Family
  // ---------------------------------------------------------------------------

  'BANE-CORE': {
    id: 'BANE-CORE',
    title: 'BANE Core Integrity Engine',
    tier: 'core',
    family: 'bane-enforcement',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'enforcement',
    capabilities: ['enforce', 'audit'],
    description:
      'Structural integrity enforcement, boundary monitoring, and unknown-path refusal logic. The system spine.',
    dependsOn: ['BANE'],
    authorityScope: 'Core structural boundary enforcement and fail-closed refusal. No reasoning.',
    permittedInputs: ['intent_vector', 'policy', 'artifacts', 'keys'],
    permittedOutputs: ['policy_flags', 'audit_events'],
    executionRestrictions: ['Must not perform domain reasoning', 'Must remain fail-closed on unknown paths'],
    auditRequirements: ['Immutable audit trail on all constraint triggers', 'Produce EngineVerdict per intervention'],
    flags: { enabledByDefault: true, canRunOffline: true, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  'BANE-POLICY': {
    id: 'BANE-POLICY',
    title: 'BANE Policy Engine',
    tier: 'core',
    family: 'bane-enforcement',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'enforcement',
    capabilities: ['enforce', 'evaluate', 'audit'],
    description:
      'Evaluates policy constraints, capability enforcement, and escalation/refusal gating.',
    dependsOn: ['BANE'],
    authorityScope: 'Policy evaluation and verdict issuance only. No domain reasoning.',
    permittedInputs: ['intent_vector', 'policy', 'keys', 'policy_flags'],
    permittedOutputs: ['policy_flags', 'audit_events'],
    executionRestrictions: ['Must not perform domain reasoning', 'Must not generate reports', 'Must not capture sensor data'],
    auditRequirements: ['Log all policy evaluations', 'Produce EngineVerdict per evaluation'],
    flags: { enabledByDefault: true, canRunOffline: false, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  'BANE-AUDIT': {
    id: 'BANE-AUDIT',
    title: 'BANE Audit Trail Engine',
    tier: 'core',
    family: 'bane-enforcement',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'audit',
    capabilities: ['audit'],
    description:
      'Immutable audit trail logic, decision-path capture, and receipt/evidence linkage.',
    dependsOn: ['BANE', 'BANE-CORE'],
    authorityScope: 'Audit trail integrity and receipt generation only. Does not authorize actions.',
    permittedInputs: ['audit_events', 'artifacts', 'policy_flags'],
    permittedOutputs: ['audit_events'],
    executionRestrictions: ['Must not enforce policy decisions', 'Must not modify source artifacts'],
    auditRequirements: ['Log all immutable evidence linkage', 'Produce EngineVerdict/Receipts on commit'],
    flags: { enabledByDefault: true, canRunOffline: true, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  'BANE-COMPLIANCE': {
    id: 'BANE-COMPLIANCE',
    title: 'BANE Compliance Engine',
    tier: 'core',
    family: 'bane-enforcement',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'enforcement',
    capabilities: ['evaluate', 'enforce', 'audit'],
    description:
      'Regulatory and corporate boundary validation, framework alignment checks, and severity classification.',
    dependsOn: ['BANE', 'BANE-POLICY'],
    authorityScope: 'Compliance alignment verification only. Drives downstream reporting/enforcement.',
    permittedInputs: ['policy', 'findings', 'artifacts', 'telemetry'],
    permittedOutputs: ['policy_flags', 'findings', 'audit_events'],
    executionRestrictions: ['Must not perform domain reasoning', 'Must not capture sensor data'],
    auditRequirements: ['Log all framework alignment violations', 'Produce EngineVerdict per compliance gate'],
    flags: { enabledByDefault: true, canRunOffline: false, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  // ---------------------------------------------------------------------------
  // Truth / Report / Audit Family
  // ---------------------------------------------------------------------------

  'LARI-STANDARDS': {
    id: 'LARI-STANDARDS',
    title: 'LARI Standards Engine',
    tier: 'core',
    family: 'truth-audit',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'reporting',
    capabilities: ['evaluate', 'report', 'audit'],
    description:
      'Aligns findings with regulatory context and industry standards (e.g. OSHA, API, ISO).',
    dependsOn: ['LARI', 'SCING-ORCH'],
    authorityScope: 'Standards alignment analysis and downstream formatting. Does not authorize actions.',
    permittedInputs: ['findings', 'policy', 'artifacts', 'classifications'],
    permittedOutputs: ['findings', 'report_blocks', 'audit_events'],
    executionRestrictions: ['Must not enforce BANE policy', 'Must remain truth-preservation layer'],
    auditRequirements: ['Log all standards alignment mappings', 'Preserve source artifact linkage'],
    flags: { enabledByDefault: true, canRunOffline: true, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  'SCING-REPORT': {
    id: 'SCING-REPORT',
    title: 'SCING Report Generator',
    tier: 'core',
    family: 'truth-audit',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'reporting',
    capabilities: ['report', 'audit'],
    description:
      'Aggregates findings into structured, investor/regulator-grade reports. Formats data for human consumption.',
    dependsOn: ['SCING-ORCH', 'BANE'],
    authorityScope: 'Report generation and formatting only. Does not reason or enforce.',
    permittedInputs: ['findings', 'classifications', 'artifacts', 'map_layers', 'report_blocks'],
    permittedOutputs: ['report_blocks', 'audit_events'],
    executionRestrictions: ['Must not perform domain reasoning', 'Must not enforce policy', 'Must not modify source findings'],
    auditRequirements: ['Log all report generation events', 'Preserve source attribution'],
    flags: { enabledByDefault: true, canRunOffline: true, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  'SCING-AUDIT': {
    id: 'SCING-AUDIT',
    title: 'SCING Audit Trail Manager',
    tier: 'core',
    family: 'truth-audit',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'audit',
    capabilities: ['audit'],
    description:
      'Records, indexes, and validates truth-artifact integrity. Produces audit summaries and chain-of-custody records.',
    dependsOn: ['BANE'],
    authorityScope: 'Audit recording and truth-artifact validation only. Does not enforce or reason.',
    permittedInputs: ['audit_events', 'artifacts', 'policy'],
    permittedOutputs: ['audit_events'],
    executionRestrictions: ['Must not enforce policy', 'Must not perform reasoning', 'Must not modify source data'],
    auditRequirements: ['Log all audit operations', 'Validate chain-of-custody integrity'],
    flags: { enabledByDefault: true, canRunOffline: false, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  // ---------------------------------------------------------------------------
  // Contractor Division Family
  // ---------------------------------------------------------------------------

  'LARI-CONTRACTOR': {
    id: 'LARI-CONTRACTOR',
    title: 'LARI Contractor Engine',
    tier: 'core',
    family: 'lari-reasoning',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'reasoning',
    capabilities: ['analyze', 'classify', 'synthesize', 'audit'],
    description:
      'Domain orchestration for contractor/subcontractor classification, compliance flow, proposal support, and oversight logic.',
    dependsOn: ['BANE', 'LARI-ORCH', 'LARI-RETRIEVER', 'LARI-STANDARDS'],
    authorityScope: 'Contractor domain orchestration and compliance reasoning only. No self-authorization of legal standing.',
    permittedInputs: ['artifacts', 'telemetry', 'findings', 'policy'],
    permittedOutputs: ['findings', 'classifications', 'report_blocks', 'audit_events'],
    executionRestrictions: ['Must not self-authorize legal conclusions', 'Must not finalize documents autonomously'],
    auditRequirements: ['Log all compliance and drafting support actions', 'Produce EngineTrace per invocation'],
    flags: { enabledByDefault: true, canRunOffline: false, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },

  'LARI-ENGINEER': {
    id: 'LARI-ENGINEER',
    title: 'LARI Engineer Engine',
    tier: 'core',
    family: 'lari-reasoning',
    runtime: 'server',
    stage: 'NA',
    executionClass: 'reasoning',
    capabilities: ['analyze', 'evaluate', 'audit'],
    description:
      'Engineering-grade reasoning escalation for structural, mechanical, and technical scope validation.',
    dependsOn: ['BANE', 'LARI-ORCH', 'LARI-CONTRACTOR'],
    authorityScope: 'Technical and engineering validation only. Does not replace licensed human authority.',
    permittedInputs: ['artifacts', 'telemetry', 'findings', 'policy'],
    permittedOutputs: ['findings', 'audit_events'],
    executionRestrictions: ['Must not replace contractor flow', 'Must not issue unreviewed technical conclusions as binding truth'],
    auditRequirements: ['Log all engineering escalation events', 'Produce EngineTrace per invocation'],
    flags: { enabledByDefault: true, canRunOffline: false, requiresExternalHardware: false },
    version: { schema: '1.0.0', impl: '0.1.0' },
  },
};
