// src/components/reporting/GlobalDisclosure.tsx
'use client';

import React from 'react';
import { Shield, AlertTriangle } from 'lucide-react';
import { cn } from '@/lib/utils';

interface GlobalDisclosureProps {
  className?: string;
  isUnverified?: boolean;
}

export default function GlobalDisclosure({ className, isUnverified = false }: GlobalDisclosureProps) {
  return (
    <div className={cn(
      "p-4 border bg-black/40 backdrop-blur-md rounded-lg space-y-3",
      isUnverified ? "border-amber-500/30" : "border-border/20",
      className
    )}>
      <div className="flex items-center gap-2">
        <Shield className="w-4 h-4 text-primary" />
        <span className="text-[10px] font-mono font-bold uppercase tracking-[0.2em] text-primary">
          SCINGULAR REPORTING DOCTRINE
        </span>
      </div>
      
      <p className="text-[11px] leading-relaxed text-muted-foreground font-medium">
        SCINGULAR provides observational intelligence and structured reporting support. 
        It does not determine correctness, compliance, or scientific authority. 
        <span className="text-foreground"> Final determination is reserved for human evaluation. </span>
        Qualified professional review remains required where applicable.
      </p>

      {isUnverified && (
        <div className="pt-2 mt-2 border-t border-amber-500/20 flex items-start gap-3">
          <AlertTriangle className="w-4 h-4 text-amber-500 mt-0.5 shrink-0" />
          <div className="space-y-1">
            <span className="text-[9px] font-mono font-bold uppercase text-amber-500 block">
              OPERATOR VERIFICATION WARNING
            </span>
            <p className="text-[10px] text-amber-200/70 leading-normal">
              This report has been generated by an unverified field operator. 
              Licensing and Certifications have not been validated.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
